meta_strategy:
  confidence_threshold: 0.7
  max_attempts: 3
  strategy_timeout: 30

concept_formation:
  min_occurrences: 5
  validation_threshold: 0.8

curriculum:
  difficulty_steps: 10
  progression_rate: 1.2

pattern_matching:
  similarity_threshold: 0.85
  max_patterns: 1000

solution_synthesis:
  max_steps: 20
  complexity_limit: 50

llm:
  model_name: "o3-mini"
  max_tokens: 1000
